### ISSUE TITLE
Erro no Jekyll serve

### ISSUE THREAD

**Issue by fersasil** [ccuffs/cc.uffs.edu.br#16]
![Capturar](https://user-images.githubusercontent.com/26921536/64713607-8f3e0c00-d493-11e9-90a8-033cd8d9f684.PNG)

**Comment by fersasil** [comment]
Quando tento iniciar o servidor aparece o erro de "method missing".

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:403:in `method_missing': undefined method `converters' for #<Jekyll::Document _pages/articles.md collection=pages> (NoMethodError)

**Comment by rifam** [comment]
No _config.yml  

Faça
```
plugins:
  - jekyll-sitemap
  - jekyll-gist
  #jekyll-feed
```
