### ISSUE TITLE
Sugestão de modificação na página "Centro acadêmico" e criação de página para grupos e canais de comunicação

### ISSUE THREAD

**Issue by Catanio** [ccuffs/cc.uffs.edu.br#19]
Quando se está procurando pelas páginas relacionadas ao curso, não me pareceu intuitivo que os canais de comunicação estejam dispostos na página do [centro acadêmico](http://cc.uffs.edu.br/ca/)
Sugiro as seguintes mudanças:

**Página do C.A:**
Pessoas que o compõem, funções e atribuições (pra enriquecer o contexto e poder direcionar dúvidas/sugestões/perguntas)
Contatos (email? link para a página de canais de comunicação?)

**Página de grupos e canais de comunicação:**
Redes sociais no geral (Telegram, Facebook, insta)
(ou ao menos com quem falar para ingressar nelas. Imagino que os aplicativos de mensagem devam ter alguma moderação nesse sentido)
<hr>
Creio que são duas coisas pra facilitar o acesso a informação. Isso incentiva a participação e a interação das pessoas do curso.

**Comment by Dovyski** [comment]
A sugestão de alteração na página do CA é excelente. Em relação à Página de Grupos e Canais de Comunicação, ela seria algo como "Comunicação" e estaria listada sob o menu "Curso"? Ou seria algo mais discreto, como um link "Canais de comunicação" no rodapé?

**Comment by Catanio** [comment]
Não havia pensado sendo um link no rodapé.

Acredito que pela explicitude seja mais interessante estar como link dentro do menu "o curso"

**Comment by dbguilherme** [comment]
Resolvido
