### ISSUE TITLE
Melhorar ilustrações

### ISSUE THREAD

**Issue by Dovyski** [ccuffs/cc.uffs.edu.br#20]
Várias ilustrações do site não receberam a atenção devida. O site [undraw.co](https://undraw.co/) tem muitas ilustrações customizáveis, grátis, que podem ser usadas.

**Comment by dbguilherme** [comment]
Com certeza, quem sabe se incluirmos algumas horas de ACCs (5 horas - por ilustração) o pessoal não se interessa :)

**Comment by joziasmartini** [comment]
Todas as ilustrações que encontrei no website são bem agradáveis. Acredito que alguém já tenha atualizado as mesmas, talvez?

**Comment by dbguilherme** [comment]
@joziasmartini Sim as ilustrações foram atualizadas mas sempre tem espaço para melhorias e avanços ;)
