### ISSUE TITLE
Links de redes sociais quebrados

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/cc.uffs.edu.br#36]
**Descreva o bug/problema**
Os links de rodapé para instagram, facebook, twitter e youtube não estão apontando para os perfis corretos.

**Reproduzir**
1. Acesse os links de redes sociais no rodapé do website

**Comment by Dovyski** [comment]
Obrigado pelo aviso. O perfil oficial do Instagram do curso será lançado esse semestre. Talvez fosse uma boa desculpa para lançar todos os outros, mesmo que em estágio inicial/embrionário.

**Comment by joziasmartini** [comment]
Atualmente, parece que todos os links estão funcionando corretamente, apenas o Facebook está redirecionando para uma página de jóias, portanto precisa ser atualizado.

Alguns pontos interessantes a serem pensados: a pessoa que resolver essa issue criará a página para o curso? Com quem ficam as contas? Elas são repassadas entre mantenedores, centro acadêmico ou coordenação?

**Comment by dbguilherme** [comment]
@joziasmartini, realmente já tinho sido resolvida. O link para o facebook será removido do site. Obrigado pela informação.
