### ISSUE TITLE
Informações incorretas sobre a monitoria

### ISSUE THREAD

**Issue by jeanchilger** [ccuffs/cc.uffs.edu.br#42]
As [informações sobre monitoria](https://cc.uffs.edu.br/ensino/monitoria/) estão desatualizadas, pelo menos para a Monitoria de Algoritmos e Programação. Talvez o professor Guilherme possa fornecer informações nesta modalidade @dbguilherme. Não sei quanto às outras modalidades, mas acredito que elas tbm estejam desatualizadas. Para a Monitoria de Circuitos Digitais e Hardware talvez o @lcaimi possa fornecer informações à respeito dos horários.

Uma sugestão é que os monitores fiquem responsáveis por informar os horários, seja atualizando o site, ou criando uma issue com os horários novos.

Se os professores (ou monitores) providenciarem os horários (e nomes/contato dos respectivos monitores) das monitorias eu me coloco à disposição para atualizar a página.

PS: Para a monitoria de cálculo seria necessário ver com o pessoal de matemática, neste caso não sei como poderia ser feito (talvez alguem com esta informação pode criar uma issue).

**Comment by jeanchilger** [comment]
Encontrei as informações sobre as monitorias neste edital: https://www.uffs.edu.br/atos-normativos/edital/acadch/2021-0005, então irei ajustar isto em uma PR.

**Comment by dbguilherme** [comment]
@jeanchilger, aguarde finalizar a seleção para atualizar com os  dados corretos. Quando tiver a versão definitiva, eu lhe informo.

**Comment by jeanchilger** [comment]
Ok, entendido!

**Comment by jeanchilger** [comment]
Há prazo para a saída deste edital?

**Comment by dbguilherme** [comment]
olá Jean, as informações com os monitores e horários estão no [link](https://docs.google.com/spreadsheets/d/18wdooo2O6rSPV0XSM-j94dK-wOxKslXu-D60ehjS4Uo/edit#gid=0)

**Comment by jeanchilger** [comment]
Certo, obrigado :hearts:

**Comment by jeanchilger** [comment]
@lcaimi este semestre haverá monitoria de circuitos?

**Comment by lcaimi** [comment]
Infelizmente não teremos. Não houve interessados.

**Comment by jeanchilger** [comment]
ok (triste :cry:)
