### ISSUE TITLE
Implementar tela de erro para sites pessoais não encontrados

### ISSUE THREAD

**Issue by vieir4ndo** [ccuffs/cc.uffs.edu.br#92]
No momento, quando um site pessoal está ativado, mas não foi clonado com sucesso, é exibido a tela de erro padrão do navegador para o erro 404.  (Imagem em anexo)

Sugere-se implementar nova tela com a seguinte mensagem:
"Está página ainda está sendo construida. Por que você não visita nosso site enquanto isso?"
Inserir redirect para pagina inicial do curso

![image](https://user-images.githubusercontent.com/55711103/119060267-3cc32b80-b9a8-11eb-9668-54eda6e6d95c.png)

**Comment by dbguilherme** [comment]
Com certeza, quem sabe se incluirmos algumas horas de ACCs (15 horas) o pessoal não se interessa :)

**Comment by riannbarbosa** [comment]
@dbguilherme , Eu já havia criado uma página de erro, so faltava adicionar na parte do servidor para o  nginx redirecionar, 
a página se encontra neste endereço `https://cc.uffs.edu.br/404/`

**Comment by dbguilherme** [comment]
@riannbarbosa, obrigado! Vou fazer isso sim :)
