### ISSUE TITLE
Página de não encontrado 404

### ISSUE THREAD

**Issue by Dovyski** [ccuffs/cc.uffs.edu.br#93]
Qualquer link quebrado no site mostra uma página branca com 404 apenas. Essa página pode receber muito mais carinho e layout.

**Comment by dbguilherme** [comment]
Com certeza, quem sabe se incluirmos algumas horas de ACCs (20 horas) o pessoal não se interessa :)

**Comment by joziasmartini** [comment]
Olá, eu utilizei parte do meu tempo tentando resolver esse problema da 404 e aqui estão algumas coisas que observei:

A página de 404 já existe e é bem bonita. Agora, ela se encontra diretamente no /404, assim:

![image](https://user-images.githubusercontent.com/31961274/187967461-9678ab9f-255d-4be1-8eef-5c4a0f21405b.png)

No entanto, como o website é hospedado no servidor próprio, eu não consigo configurar as páginas de erro.

Seguindo [este tutorial](https://jekyllrb.com/tutorials/custom-404-page/) do Jekyll, é necessário editar o .htaccess e incluir o link para a 404.html nele.

Ela fica no endereço `../_site/404/index.html`, como na solução parcial commitada por mim anteriormente.

Alguém de vocês consegue fazer isso, por favor? @Dovyski @dbguilherme

**Comment by riannbarbosa** [comment]
Exatamente @joziasmartini, eu fiz essa página de erro a um tempo atrás e também avisei ao @Dovyski  que faltava adicionar nesta parte do servidor ( editando o .htaccess) para que seja redirecionado a esta página e não ao 404 padrão.

**Comment by dbguilherme** [comment]
Obrigado @riannbarbosa e @joziasmartini  foi erro de comunicação mesmo, sorry!
